CMMS/CMMS/Areas/Management/Controllers/ActiveSessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using CMMS.Controllers;
using CMMS.Pages;
using Kendo.Mvc.UI;
using CMMS.Infrastructure;
using CMMS.Model;
using CMMS.Service;

namespace CMMS.Areas.Management.Controllers
{
    /// <summary>
    /// Active Session Controller
    /// </summary>
    public partial class ManagementController : BaseController
    {
        /// <summary>
        /// Actives the session.
        /// </summary>
        /// <returns></returns>
        [ActionName(Actions.ActiveSession)]
        public ActionResult ActiveSession()
        {
            if (ProjectSession.PermissionAccess.Management_ActiveSessions_Allowaccess && ProjectSession.PermissionAccess.Management__ShowHideModule)
            {
                return View(Views.ActiveSession);
            }
            else
            {
                return RedirectToAction(Actions.AccessDenied, Pages.Controllers.Account, new { area = string.Empty });
            }
        }

        /// <summary>
        /// Gets the active session.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        [ActionName(Actions.GetActiveSession)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetActiveSession([DataSourceRequest]DataSourceRequest request)
        {
            string sortExpression = string.Empty;
            string sortDirection = string.Empty;

            if (request.Sorts.Count > 0)
            {
                sortExpression = request.Sorts[0].Member;
                sortDirection = request.Sorts[0].SortDirection == ListSortDirection.Ascending ? "Ascending" : "Descending";
            }
            else
            {
                sortExpression = "Logintime";
                sortDirection = "Ascending";
            }

            int pageNumber = request.Page;
            ProjectSession.PageSize = request.PageSize;

            Session sessionSearch = new Session();

            SearchFieldService obj = new SearchFieldService();
            var result = new DataSourceResult()
            {
                Data = obj.AdvanceSearch(sessionSearch, SystemEnum.Pages.ActiveSession.GetHashCode(), ProjectSession.EmployeeID, pageNumber, sortExpression, sortDirection, request: request),
                Total = obj.PagingInformation.TotalRecords
            };
            return Json(result);
        }

        /// <summary>
        /// Deletes the active session.
        /// </summary>
        /// <param name="sessionId">The session identifier.</param>
        /// <returns></returns>
        [ActionName(Actions.DeleteActiveSession)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteActiveSession(int sessionId)
        {
            using (DapperContext context = new DapperContext())
            {
                int returnValue = context.Delete<Session>(sessionId, true);
                if (returnValue == 0)
                {
                    return Json(new object[] { SystemEnum.MessageType.success.ToString(), ProjectSession.Resources.message.Common_MsgCommonRecordDeletedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
                else if (returnValue == -2)
                {
                    return Json(new object[] { SystemEnum.MessageType.danger.ToString(), ProjectSession.Resources.message.Common_MsgReferencedInOtherModules }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new object[] { SystemEnum.MessageType.danger.ToString(), ProjectSession.Resources.message.Common_MsgErrorContactAdmin }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

CMMS/CMMS/Areas/Management/Controllers/DatabaseAuditTrailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMMS.Controllers;
using CMMS.Pages;
using CMMS.Infrastructure;
using CMMS.Model;
using CMMS.Service;
using Kendo.Mvc.UI;
using CMMS.Services;

namespace CMMS.Areas.Management.Controllers
{
    /// <summary>
    /// Database Audit Trail Controller
    /// </summary>
    public partial class ManagementController : BaseController
    {
        /// <summary>
        /// Actives the session.
        /// </summary>
        /// <returns></returns>
        [ActionName(Actions.DatabaseAuditTrail)]
        public ActionResult DatabaseAuditTrail()
        {
            if (ProjectSession.PermissionAccess.Management_AuditTrail_Allowaccess && ProjectSession.PermissionAccess.Management__ShowHideModule)
            {
                return View(Views.DatabaseAuditTrail);
            }
            else
            {
                return RedirectToAction(Actions.AccessDenied, Pages.Controllers.Account, new { area = string.Empty });
            }
        }

        /// <summary>
        /// get name by property
        /// </summary>
        /// <param name="lstColumnName">list of column name</param>
        /// <param name="tableName">Table Name of property</param>
        /// <returns></returns>
        [ActionName(Actions.GetPropertyName)]
        public string GetPropertyNameList(string lstColumnName, string tableName)
        {
            string finalTranslate = string.Empty;
            List<string> columnNames = Newtonsoft.Json.JsonConvert.DeserializeObject<List<string>>(lstColumnName);
            List<string> translateNames = new List<string>();

            foreach (string property in columnNames)
            {
                string propertyCmp = property.ToLower();
                string propertyName = "AuditTrail_" + tableName.ToLower() + "_" + property.ToLower();
                try
                {
                    if (!(propertyCmp == "modifiedby" || propertyCmp == "modifieddate"))
                    {
                        ////AuditTrail_workorders_workorderno
                        var translateProperty = ProjectSession.Resources.audit.GetType().GetProperty(propertyName).GetValue(ProjectSession.Resources.audit).ToString();
                        translateNames.Add(translateProperty);
                    }
                    else if (propertyCmp == "modifiedby")
                    {
                        var translateProperty = ProjectSession.Resources.label.GetType().GetProperty("ItemRequisition_TextBlockModifiedBy").GetValue(ProjectSession.Resources.label).ToString();
                        translateNames.Add(translateProperty);
                    }
                    else if (propertyCmp == "modifieddate")
                    {
                        var translateProperty = ProjectSession.Resources.label.GetType().GetProperty("ItemRequisition_TextBlockModifiedDate").GetValue(ProjectSession.Resources.label).ToString();
                        translateNames.Add(translateProperty);
                    }
                    else
                    {
                        translateNames.Add(property);
                    }
                }
                catch
                {
                    translateNames.Add(property);
                }
            }

            finalTranslate = Newtonsoft.Json.JsonConvert.SerializeObject(translateNames);
            return finalTranslate;
        }

        /// <summary>
        /// Delete all record from selected table
        /// </summary>
        /// <param name="tableName">Delete all record from table by tableName</param>
        /// <returns></returns>
        [ActionName(Actions.DeleteAuditTablesAllRecords)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteAuditTablesAllRecords(string tableName)
        {
            if (!string.IsNullOrEmpty(tableName))
            {
                DatabaseAuditTrailServices context = new DatabaseAuditTrailServices();

                tableName = "CDC.dbo_" + tableName + "_CT";

                bool returnValue = context.DeleteAuditTrialAllRecords(tableName);

                if (returnValue)
                {
                    return Json(new object[] { SystemEnum.MessageType.success.ToString(), ProjectSession.Resources.message.Common_MsgCommonRecordDeletedSuccessfully }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new object[] { SystemEnum.MessageType.danger.ToString(), ProjectSession.Resources.message.Common_MsgErrorContactAdmin }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new object[] { SystemEnum.MessageType.danger.ToString(), ProjectSession.Resources.message.Common_MsgErrorContactAdmin }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Get Asset Details By AssetID
        /// </summary>
        /// <param name="tableName">The AssetDetails identifier</param>
        /// <param name="searchType">The AssetDetails </param>
        /// <returns></returns>
        [ActionName(Actions.GetDatabaseAuditTableDetails)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult GetDatabaseAuditTableDetails(string tableName, string searchType)
        {
            string strWhere = string.Empty;
            string query = string.Empty;
            tableName = tableName.ToLower();
            if (!(string.IsNullOrEmpty(searchType) || searchType == "null"))
            {
                searchType = HttpUtility.UrlDecode(searchType);
                strWhere = "and __$operation in (" + searchType + ")";
            }

            DatabaseAuditTrailServices context = new DatabaseAuditTrailServices();

            DataSourceResult dataSourceResult = null;

            switch (tableName)
            {
                case "workorders":
                    dataSourceResult = new DataSourceResult()
                {
                    Data = context.GetDataBaseAuditTrial<Dbo_workorders_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "assigntoworkorder":
                    dataSourceResult = new DataSourceResult()
                {
                    Data = context.GetDataBaseAuditTrial<Dbo_assigntoworkorder_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "workorderlabor":
                    dataSourceResult = new DataSourceResult()
                     {
                         Data = context.GetDataBaseAuditTrial<Dbo_workorders_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                     };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "direct":
                    dataSourceResult = new DataSourceResult()
               {
                   Data = context.GetDataBaseAuditTrial<Dbo_direct_CT>(0, strWhere, string.Empty, string.Empty, tableName)
               };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "issue":
                    dataSourceResult = new DataSourceResult()
                {
                    Data = context.GetDataBaseAuditTrial<Dbo_issue_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "return":
                    dataSourceResult = new DataSourceResult()
                {
                    Data = context.GetDataBaseAuditTrial<Dbo_return_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "workorderelements":
                    dataSourceResult = new DataSourceResult()
               {
                   Data = context.GetDataBaseAuditTrial<Dbo_workorderelements_CT>(0, strWhere, string.Empty, string.Empty, tableName)
               };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "workorderitems":
                    dataSourceResult = new DataSourceResult()
                   {
                       Data = context.GetDataBaseAuditTrial<Dbo_workorderitems_CT>(0, strWhere, string.Empty, string.Empty, tableName)
                   };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "jobtask":
                    dataSourceResult = new DataSourceResult()
              {
                  Data = context.GetDataBaseAuditTrial<Dbo_jobtask_CT>(0, strWhere, string.Empty, string.Empty, tableName)
              };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "sitask":
                    dataSourceResult = new DataSourceResult()
               {
                   Data = context.GetDataBaseAuditTrial<Dbo_sitask_CT>(0, strWhere, string.Empty, string.Empty, tableName)
               };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "extassetfiles_j":
                    dataSourceResult = new DataSourceResult()
               {
                   Data = context.GetDataBaseAuditTrial<Dbo_extassetfiles_CT>(0, strWhere, string.Empty, string.Empty, tableName)
               };
                    return Json(dataSourceResult.Data, JsonRequestBehavior.AllowGet);

                case "assets":
                    dataSourceResult = new DataSourceResult()
                 {

CMMS/CMMS/Areas/Management/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMMS.Controllers;

namespace CMMS.Areas.Management.Controllers
{
    /// <summary>
    /// Management Controller
    /// </summary>
    public partial class ManagementController : BaseController
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

CMMS/CMMS/Controllers/GridExportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMMS.Controllers
{
    /// <summary>
    /// Grid Export controller
    /// </summary>
    public class GridExportController : Controller
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Excel_s the export_ save.
        /// </summary>
        /// <param name="contentType">Type of the content.</param>
        /// <param name="base64">The base64.</param>
        /// <param name="fileName">Name of the file.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Excel_Export_Save(string contentType, string base64, string fileName)
        {
            var fileContents = Convert.FromBase64String(base64);

            return File(fileContents, contentType, fileName);
        }
    }
}

CMMS/CMMS/Areas/Management/Views/Management/ActiveSession.cshtml
@using CMMS.Infrastructure;
@using CMMS.Pages;
@{
    ViewBag.Title = "ActiveSession";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.AntiForgeryToken()
<div class="head1">
    <h1>@ProjectSession.Resources.label.Employee_TextBlockActiveSession</h1>
    <ul class="sub_btn">
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-search" data-toggle="modal" data-target="#search-order" onclick='OpenAdvancedSearch("@ProjectSession.Resources.label.Employee_TextBlockActiveSession","@SystemEnum.Pages.ActiveSession.GetHashCode()");' title="@ProjectSession.Resources.label.Common_ButtonAdvanceSearch"><i></i></a>
        </li>
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-clear" title="@ProjectSession.Resources.label.Common_ButtonClear" onclick="return ClearAdvencedSearch(@SystemEnum.Pages.ActiveSession.GetHashCode());"><i></i></a>
        </li>
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-refresh" onclick="ReBindKendoGrid('activeSessionGrid');" title="@ProjectSession.Resources.label.Common_ButtonRefreshGrid"><i></i></a>
        </li>
        @if (ProjectSession.PermissionAccess.Management_ActiveSessions_Export)
        {
            <li>
                <a href="javascript:void(0);" class="btn-icon btn-xsl" onclick="ExportToExcel('activeSessionGrid', 'SessionId');" title="@ProjectSession.Resources.label.Common_ButtonExportToExcel"><i></i></a>
            </li>
        }
    </ul>
</div>

<!-- Kendo Grid-->
<div id="activeSessionData" class="@ProjectSession.CultureKendoClass">
    @(Html.Kendo().Grid<CMMS.Model.Session>()
        .HtmlAttributes(new { @class = "kl-grid" })
        .Name("activeSessionGrid")
        .Columns(columns =>
        {
            columns.Bound(c => c.EmployeeNO).Title(ProjectSession.Resources.label.Employee_TextBlockEmployeeNO).Width(100);

            columns.Bound(c => c.NAME).Title(ProjectSession.Resources.label.Employee_TextBlockEmployeeName);

            columns.Bound(c => c.L2Code).Title(ProjectSession.Resources.label.JobRequest_TextBlockCityCode)
            .Filterable(ftb => ftb.Multi(true).DataSource(ds => ds.Read(r => r.Action("FilterSite", "GridFilter", new { area = string.Empty }).Data("BindParameters").Type(HttpVerbs.Post))));

            columns.Bound(c => c.Logintime).ClientTemplate("#= DateTemplateWithTime(data.Logintime) #").Title(ProjectSession.Resources.label.Employee_TextBlockLoginDateTime);

            if (ProjectSession.PermissionAccess.Management_ActiveSessions_Deleterecords)
            {
                columns.Bound(c => c.SessionId).ClientTemplate("<center><a class='action delete-button'  href='javascript:void(0);'  class='delete-ic' data-id='#: SessionId #' style='cursor:pointer'><i class='glyphicon glyphicon-trash' title='" + ProjectSession.Resources.label.Common_ButtonDelete + "'></i></a></center>")
                                            .Title("<center>" + ProjectSession.Resources.label.Common_ButtonAction + "</center>").HtmlAttributes(new { @class = "action" }).Sortable(false).Width(70).Filterable(false);
            }
        })
        .Filterable()
        .Sortable(sortable => sortable.AllowUnsort(false))
        .Scrollable()
        .Excel(excel => excel.FileName("Active Session.xlsx").Filterable(true).AllPages(true).ProxyURL(Url.Action("Excel_Export_Save", "GridExport", new { area = string.Empty })))
        .Pageable(pageable => pageable.PageSizes(General.PageSizes).ButtonCount(5).Messages(m => m.ItemsPerPage("").Display(ProjectSession.Resources.message.Common_MsgDisplayRecords)))
        .Events(events => events.DataBound("onDataBound").ExcelExport("excelExport"))
        .DataSource(dataSource =>
                                dataSource.Ajax()
                                .PageSize(ProjectConfiguration.PageSize)
                                .Sort(model => model.Add("Logintime").Descending())
                                 .Model(model =>
                                 {
                                     model.Id(p => p.SessionId);
                                     model.Field(p => p.Logintime);
                                 })
                                .ServerOperation(true)
                                .Read(read => read.Action(Actions.GetActiveSession, Controllers.Management, new { area = Areas.Management }).Data("BindParameters").Type(HttpVerbs.Post))
        )
    )

</div>

<!-- search order -->
<div id="search-order" class="modal fade" role="dialog"></div>

<script type="text/javascript">
    var kendoGridId = 'activeSessionGrid';
    var intPageID = '@SystemEnum.Pages.ActiveSession.GetHashCode()';

    function BindParameters() {
        return {
            __RequestVerificationToken: $('input[name=__RequestVerificationToken]').val()
        };
    }

    function addRequestVerificationToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    };
</script>

@if (ProjectSession.PermissionAccess.Management_ActiveSessions_Deleterecords)
{
    <script type="text/javascript">
        function onDataBound(arg) {
            confirmDeleteMsg(msgText, okText, cancelText, onConfirmCallback, confirmDirection);
            gridProperPaging(this);
        }

        function onConfirmCallback(sender) {
            var id = $(this).data("id");
            $.ajax({
                url: '@Url.Action(Actions.DeleteActiveSession, Controllers.Management, new { area = Areas.Management })',
                type: "POST",
                data: addRequestVerificationToken({ sessionId: id }),
                dataType: "json",
                success: function (result) {
                    ShowMessage(result[0], result[1], "#divMessage");
                    ReBindKendoGrid("activeSessionGrid");
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    showErrorMessage();
                }
            });
        }
    </script>
}
else
{
    <script>
        function onDataBound(arg) {
            gridProperPaging(this);
        }
    </script>
}

CMMS/CMMS/Areas/Management/Views/Management/LoginHistory.cshtml
@using CMMS.Infrastructure;
@using CMMS.Pages;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.AntiForgeryToken()
<div class="head1">
    <h1>@ProjectSession.Resources.label.Employee_TextBlockLoginHistoryList</h1>
    <ul class="sub_btn">
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-search" data-toggle="modal" data-target="#search-order" onclick='OpenAdvancedSearch("@ProjectSession.Resources.label.Employee_TextBlockLoginHistoryList","@SystemEnum.Pages.LoginHistory.GetHashCode()");' title="@ProjectSession.Resources.label.Common_ButtonAdvanceSearch"><i></i></a>
        </li>
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-clear" title="@ProjectSession.Resources.label.Common_ButtonClear" onclick="return ClearAdvencedSearch(@SystemEnum.Pages.LoginHistory.GetHashCode());"><i></i></a>
        </li>
        <li>
            <a href="javascript:void(0);" class="btn-icon btn-refresh" onclick="ReBindKendoGrid('loginHistoryGrid');" title="@ProjectSession.Resources.label.Common_ButtonRefreshGrid"><i></i></a>
        </li>
        @if (ProjectSession.PermissionAccess.Management_LoginHistory_Export)
        {
            <li>
                <a href="javascript:void(0);" class="btn-icon btn-xsl" onclick="ExportToExcel('loginHistoryGrid', 'LoginLogIn');" title="@ProjectSession.Resources.label.Common_ButtonExportToExcel"><i></i></a>
            </li>
        }
    </ul>
</div>

<!-- Kendo Grid-->
<div id="activeSessionData" class="@ProjectSession.CultureKendoClass">
    @(Html.Kendo().Grid<CMMS.Model.LoginLog>()
        .HtmlAttributes(new { @class = "kl-grid" })
        .Name("loginHistoryGrid")
        .Columns(columns =>
        {
            columns.Bound(c => c.NAME).Title(ProjectSession.Resources.label.Employee_TextBlockEmployeeName).Width(250);

            columns.Bound(c => c.LoginDateTime).ClientTemplate("#= DateTemplateWithTime(data.LoginDateTime) #").Title(ProjectSession.Resources.label.Employee_TextBlockLoginDateTime);

            columns.Bound(c => c.LogoutDateTime).ClientTemplate("#= DateTemplateWithTime(data.LogoutDateTime) #").Title(ProjectSession.Resources.label.Employee_TextBlockLogOutDateTime);

            columns.Bound(c => c.IPAddress).Title(ProjectSession.Resources.label.Employee_TextBlockIpAddress);
        })
        .Filterable()
        .Sortable(sortable => sortable.AllowUnsort(false))
        .Scrollable()
        .Excel(excel => excel.FileName("Login History.xlsx").Filterable(true).AllPages(true).ProxyURL(Url.Action("Excel_Export_Save", "GridExport", new { area = string.Empty })))
        .Pageable(pageable => pageable.PageSizes(General.PageSizes).ButtonCount(5).Messages(m => m.ItemsPerPage("").Display(ProjectSession.Resources.message.Common_MsgDisplayRecords)))
        .Events(events => events.DataBound("onDataBound").ExcelExport("excelExport"))
        .DataSource(dataSource =>
                                dataSource.Ajax()
                                .PageSize(ProjectConfiguration.PageSize)
                                .Sort(model => model.Add("LoginDateTime").Descending())
                                 .Model(model =>
                                 {
                                     model.Id(p => p.LoginLogIn);
                                     model.Field(p => p.LoginDateTime);
                                 })
                                .ServerOperation(true)
                                .Read(read => read.Action(Actions.GetLoginHistory, Controllers.Management, new { area = Areas.Management }).Data("BindParameters").Type(HttpVerbs.Post))
        )
    )

</div>

<!-- search order -->
<div id="search-order" class="modal fade" role="dialog"></div>

<script type="text/javascript">
    var kendoGridId = 'loginHistoryGrid';
    var intPageID = '@SystemEnum.Pages.LoginHistory.GetHashCode()';

    function BindParameters() {
        return {
            __RequestVerificationToken: $('input[name=__RequestVerificationToken]').val()
        };
    }

    function addRequestVerificationToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    };

    function onDataBound(arg) {
        gridProperPaging(this);
    }

</script>